---
pkgRoot: src

branches:
- '+([0-9])?(.{+([0-9]),x}).x'
- main
- next
- name: beta
  prerelease: true
- name: alpha
  prerelease: true

plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/git"
- - "@semantic-release/exec"
  # - prepareCmd: npx rjp package.json version nextRelease.versiong
- - "@semantic-release/git"
  - message: Release <%= nextRelease.version %> [skip ci]
    assets:
    - src/**/*.{js,svelte,css}
    - package.json
    - CHANGELOG.md
    - README.md
- "@semantic-release/changelog"