name: Automated Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  sentry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        pnpm-version: [6.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Intall pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ matrix.pnpm-version }}    
    - name: Install dependencies
      run: pnpm i
    - name: Run tests
      run: pnpm test
      
